uploaded the read me file
YusufBolden/pod3_repo pull request #1
Opened 2021-09-14 00:49 UTC by psmithxoxo43

I did it!

2021-09-14 14:32 UTC, YusufBolden requested changes
Great job on setting this up. Now I want you to get practice on making changes based on code review. Add a few more lines to your README.md file

2021-09-16 21:29 UTC, psmithxoxo43 reviewed
i tried to git push the updated read me and its saying remote rejected failed to push

2021-09-16 22:05 UTC, psmithxoxo43 commented
check out my python submission thank you! Let me know if any changes need to be made.

2021-09-17 00:11 UTC, YusufBolden approved these changes

2021-09-17 00:11 UTC, merged