Update README.md
YusufBolden/pod3_repo pull request #5
Opened 2021-09-14 01:25 UTC by Suenodivino

This is my first push to the repo.

2021-09-14 14:34 UTC, YusufBolden requested changes
Great job on setting this up. Now I want you to get practice on making changes based on code review. Add a few more lines to your README.md file

2021-09-16 03:37 UTC, Suenodivino reviewed
@YusufBolden Is this the change you requested in my file?

2021-09-16 03:37 UTC, Suenodivino commented on Dario/README.md
> +This is the new line you asked me to add to this file.
@YusufBolden This is my new line

2021-09-17 09:26 UTC, YusufBolden approved these changes
Nice work

2021-09-17 09:26 UTC, merged